'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PLS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Steamworks已连接=已连接到 Steam：{0}
        '''Steamworks未连接=无法连接到 Steam
        '''Steamworks在写入物品ID时发生错误=将 ID 写入清单时发生错误：{0}。注意物品 {1} 已经创建成功，是否重试写入？如果取消将不会上传内容并就此终止，Steam 上的物品将成为一个空物品！
        '''Steamworks已创建物品=已创建新物品：{0}
        '''Steamworks创建物品失败=创建物品时发生类型为 {0} 的错误
        '''Steamworks物品信息已更新=已更新物品信息：{0}，正在让 Steam 上传
        '''Steamworks上传成功=Steam 已完成上传物品：{0}
        '''Steamworks上传失败=上传时发生类型为 {0} 的错误
        '''Steamworks取消订阅成功=已取消订阅物品：{0}
        '''Steamworks取消订阅失败=取消订阅时发生类型为 {0} 的错误
        '''
        '''
        '''当前没有载入模组=当前没有载入模组
        '''当前模组文件夹显示=当前模组文件夹：
        '''未保存的工作将丢失=请确认你当前模组的数据已经保存到硬盘，继续操作会让未保存的工作丢失不可恢复
        '''选择新模组保存位置=选择新模组保存 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property SimplifiedChinese() As String
            Get
                Return ResourceManager.GetString("SimplifiedChinese", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
